FROM rust as builder

WORKDIR /usr/src/build

COPY . .

RUN cargo build --release

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bookworm-run

RUN install_packages iptables

WORKDIR /usr/src/run

COPY --from=builder /usr/src/build/target/release/iptables-racing-2581 .

CMD ["./iptables-racing-2581"]

